[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
markers =
    unit: unit tests
    integration: integration tests
    asyncio: mark test to run using asyncio
addopts = --asyncio-mode=auto 